services:
  employees-service:
    build: employees-service
    hostname: employees-service
#    ports:
#      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy

  api-gateway:
    build: api-gateway
    hostname: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - employees-service
      - inventory-service
      - stores-service
      - sales-service

  sales-service:
    build: sales-service
    hostname: sales-service
#    ports:
#      - "8084:8080"useruser
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - employees-service
      - inventory-service
      - stores-service


  inventory-service:
    build: inventory-service
    hostname: inventory-service
#    ports:
#      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    depends_on:
      mysql2:
        condition: service_healthy

  stores-service:
    build: stores-service
    hostname: stores-service
#    ports:
#      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres1:
        condition: service_healthy


  mysql1:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=employees-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10




  phpmyadmin1:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin1
    links:
      - mysql1
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

  mysql2:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=inventory-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql2:/var/lib/mysql2
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10




  phpmyadmin2:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin2
    links:
      - mysql2
    restart: always
    ports:
      - 5014:80
    environment:
      - PMA_ARBITRARY=1



  postgres1:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=user
        - PGUSER=user
        - POSTGRES_PASSWORD=pwd
        - POSTGRES_DB=stores-db
    healthcheck:
        test: "pg_isready -h postgres1"
        interval: 10s
        timeout: 5s
        retries: 10

  pgadmin1:
    image: dpage/pgadmin4:latest
    container_name: pgadmin1
    restart: always
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@velozo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres1

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongo_db
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pwd


  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: always
    ports:
      - 8085:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongodb:27017


volumes:
  mongo: { }